#!/usr/bin/env bash

#get name of the current directory
NAME=$(basename "$PWD")

#run the docker
docker run --name $NAME --network robomatic -p 5000:5000 -v /home/edgar/robomatic/github/evidence:/home/evidence $NAME
